from pathlib import Path
import re

def edit(path, fn):
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    new = fn(text)
    if new == text:
        raise RuntimeError(f"{path}: transformation made no change")
    p.write_text(new, encoding="utf-8")

def one(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected 1 match, got {count}")
    return text.replace(old, new, 1)

def local_view(text):
    text = one(text, '  int _decoderModeIndex = 0;\n  int _benchmarkSeconds = 10;\n  bool _benchmarking = false;\n', '  int _decoderModeIndex = 0;\n  int _benchmarkSeconds = 10;\n  double _benchmarkSpeed = 10.0;\n  bool _showAllDecoders = false;\n  bool _benchmarking = false;\n', 'local fields')
    text = one(text, '    final result = _lastBenchmark;\n\n    return Padding(\n', '    final result = _lastBenchmark;\n    final visibleModeIndexes = <int>[\n      for (final (index, mode) in modes.indexed)\n        if (_showAllDecoders || mode.primary || index == _decoderModeIndex) index,\n    ];\n\n    return Padding(\n', 'local visible modes')
    text = one(text, '                  children: List.generate(modes.length, (index) {\n                    final mode = modes[index];\n', '                  children: List.generate(visibleModeIndexes.length, (visibleIndex) {\n                    final index = visibleModeIndexes[visibleIndex];\n                    final mode = modes[index];\n', 'local mode loop')
    text = one(text, '                ),\n              ),\n              Wrap(\n                spacing: 7,\n', "                ),\n              ),\n              Align(\n                alignment: Alignment.centerLeft,\n                child: TextButton.icon(\n                  onPressed: _benchmarking\n                      ? null\n                      : () => setState(() => _showAllDecoders = !_showAllDecoders),\n                  icon: Icon(\n                    _showAllDecoders ? Icons.expand_less : Icons.expand_more,\n                    size: 18,\n                  ),\n                  label: Text(\n                    _showAllDecoders\n                        ? '收起更多解码器'\n                        : '展开全部 ${modes.length - 1} 个解码器',\n                  ),\n                ),\n              ),\n              Wrap(\n                spacing: 7,\n", 'local expand button')
    text = one(text, '                  PopupMenuButton<int>(\n                    enabled: !_benchmarking,\n                    initialValue: _benchmarkSeconds,\n', "                  PopupMenuButton<double>(\n                    enabled: !_benchmarking,\n                    initialValue: _benchmarkSpeed,\n                    onSelected: (value) {\n                      setState(() => _benchmarkSpeed = value);\n                    },\n                    itemBuilder: (context) => const [\n                      PopupMenuItem(value: 0.0, child: Text('不改变')),\n                      PopupMenuItem(value: 4.0, child: Text('4×')),\n                      PopupMenuItem(value: 6.0, child: Text('6×')),\n                      PopupMenuItem(value: 8.0, child: Text('8×')),\n                      PopupMenuItem(value: 10.0, child: Text('10×')),\n                      PopupMenuItem(value: 12.0, child: Text('12×')),\n                      PopupMenuItem(value: 13.5, child: Text('13.5×')),\n                      PopupMenuItem(value: 15.0, child: Text('15×')),\n                      PopupMenuItem(value: 16.0, child: Text('16×')),\n                    ],\n                    child: Chip(\n                      label: Text(\n                        _benchmarkSpeed == 0\n                            ? '倍速：不改变'\n                            : '倍速：${_benchmarkSpeed.toStringAsFixed(_benchmarkSpeed % 1 == 0 ? 0 : 1)}×',\n                      ),\n                    ),\n                  ),\n                  PopupMenuButton<int>(\n                    enabled: !_benchmarking,\n                    initialValue: _benchmarkSeconds,\n", 'local speed picker')
    text = one(text, "      _labMessage =\n          '${mode.label}：按当前 ${player.playbackSpeed.toStringAsFixed(2)}× 跑 $_benchmarkSeconds 秒…';\n", "      final target = _benchmarkSpeed == 0\n          ? '当前 ${player.playbackSpeed.toStringAsFixed(2)}×'\n          : '${_benchmarkSpeed.toStringAsFixed(_benchmarkSpeed % 1 == 0 ? 0 : 1)}×';\n      _labMessage = '${mode.label}：按 $target 跑 $_benchmarkSeconds 秒…';\n", 'local benchmark message')
    text = one(text, '      final result = await player.runDecoderBenchmark(\n        mode: mode,\n        wallTime: Duration(seconds: _benchmarkSeconds),\n      );\n', '      final result = await player.runDecoderBenchmark(\n        mode: mode,\n        targetSpeed: _benchmarkSpeed == 0 ? null : _benchmarkSpeed,\n        wallTime: Duration(seconds: _benchmarkSeconds),\n      );\n', 'local benchmark call')
    return text

def controller(text):
    text = one(text, "import 'package:PiliPlus/services/download/download_service.dart';\nimport 'package:PiliPlus/services/playback_stats_service.dart';\n", "import 'package:PiliPlus/services/download/download_service.dart';\nimport 'package:PiliPlus/services/cdn_last_video_service.dart';\nimport 'package:PiliPlus/services/playback_stats_service.dart';\n", 'controller import')
    text = one(text, '  List<CDNService> _cdnPriority = const [CDNService.backupUrl];\n  int _cdnIndex = 0;\n  bool _cdnFallbackInProgress = false;\n', '  List<CDNService> _cdnPriority = const [CDNService.backupUrl];\n  int _cdnIndex = 0;\n  bool _cdnFallbackInProgress = false;\n  CDNService? _manualCdn;\n  String? _manualCdnPlaybackKey;\n', 'controller fields')
    text = one(text, '  CDNService get _currentCdn =>\n      _cdnPriority.getOrNull(_cdnIndex) ?? _cdnPriority.first;\n\n  void _resetCdnPriority(NetworkProfile profile) {\n    _cdnPriority = List.of(\n      profile.useCellularPreferences\n          ? Pref.defaultCDNServicesCellular\n          : Pref.defaultCDNServices,\n    );\n    _cdnIndex = 0;\n  }\n', "  String get _cdnPlaybackKey => '$bvid:${cid.value}';\n\n  CDNService get _currentCdn =>\n      _cdnPriority.getOrNull(_cdnIndex) ?? _cdnPriority.first;\n\n  CDNService get currentCdn => _currentCdn;\n\n  bool get isCdnLockedForCurrentPlayback =>\n      _manualCdn != null && _manualCdnPlaybackKey == _cdnPlaybackKey;\n\n  Future<void> selectCdnForCurrentPlayback(CDNService cdn) async {\n    final wasPlaying = plPlayerController.playerStatus.isPlaying;\n    playedTime = plPlayerController.videoPlayerController?.state.position;\n    _manualCdn = cdn;\n    _manualCdnPlaybackKey = _cdnPlaybackKey;\n    _cdnPriority = [cdn];\n    _cdnIndex = 0;\n    _cdnFallbackInProgress = false;\n\n    if (data.dash != null) {\n      _selectPreferredStreams();\n    } else if (data.durl case final durl?) {\n      _selectLegacyStreams(durl);\n    }\n    SmartDialog.showToast('本次播放已锁定：${cdn.desc}');\n    await playerInit(autoplay: wasPlaying);\n  }\n\n  void _resetCdnPriority(NetworkProfile profile) {\n    if (_manualCdnPlaybackKey == _cdnPlaybackKey && _manualCdn != null) {\n      _cdnPriority = [_manualCdn!];\n      _cdnIndex = 0;\n      return;\n    }\n    _manualCdn = null;\n    _manualCdnPlaybackKey = null;\n    _cdnPriority = List.of(\n      profile.useCellularPreferences\n          ? Pref.defaultCDNServicesCellular\n          : Pref.defaultCDNServices,\n    );\n    _cdnIndex = 0;\n  }\n", 'controller cdn lock')
    text = one(text, '        _selectPreferredStreams();\n        await _initPlayerIfNeeded(autoFullScreenFlag);\n', '        _selectPreferredStreams();\n        unawaited(\n          CdnLastVideoService.remember(\n            bvid: bvid,\n            cid: cid.value,\n            quality: currentVideoQa.value!.code,\n            preferredCodec: currentDecodeFormats.name,\n            videoType: _actualVideoType ?? videoType,\n            tryLook: plPlayerController.tryLook,\n            epId: epId,\n            seasonId: seasonId,\n          ),\n        );\n        await _initPlayerIfNeeded(autoFullScreenFlag);\n', 'controller remember')
    return text

def video_settings(text):
    text = one(text, "import 'package:PiliPlus/pages/setting/widgets/ordered_multi_select_dialog.dart';\nimport 'package:PiliPlus/pages/setting/widgets/select_dialog.dart';\n", "import 'package:PiliPlus/pages/setting/widgets/ordered_multi_select_dialog.dart';\nimport 'package:PiliPlus/pages/setting/widgets/cdn_speed_setup_dialog.dart';\nimport 'package:PiliPlus/pages/setting/widgets/select_dialog.dart';\n", 'settings import')
    text = one(text, '  final speedConfig = Pref.cdnSpeedTest\n      ? await showCdnSpeedConfigDialog(context)\n      : null;\n  if (Pref.cdnSpeedTest && speedConfig == null || !context.mounted) return;\n  final res = await showDialog<List<CDNService>>(\n    context: context,\n    builder: (context) => CdnSelectDialog(\n      initValues: cellular\n          ? Pref.defaultCDNServicesCellular\n          : Pref.defaultCDNServices,\n      speedConfig: speedConfig,\n    ),\n  );\n', '  final speedSetup = Pref.cdnSpeedTest\n      ? await showCdnSpeedSetupDialog(context)\n      : null;\n  if (!context.mounted) return;\n  final res = await showDialog<List<CDNService>>(\n    context: context,\n    builder: (context) => CdnSelectDialog(\n      sample: speedSetup?.sample,\n      initValues: cellular\n          ? Pref.defaultCDNServicesCellular\n          : Pref.defaultCDNServices,\n      speedConfig: speedSetup?.config,\n    ),\n  );\n', 'settings cdn flow')
    return text

def header(text):
    text = one(text, "import 'package:PiliPlus/pages/video/widgets/header_mixin.dart';\nimport 'package:PiliPlus/plugin/pl_player/controller.dart';\n", "import 'package:PiliPlus/pages/video/widgets/header_mixin.dart';\nimport 'package:PiliPlus/pages/video/widgets/playback_cdn_dialog.dart';\nimport 'package:PiliPlus/plugin/pl_player/controller.dart';\n", 'header import')
    pattern = re.compile("                if \\(!isFileSource\\)\\n                  ListTile\\(\\n                    dense: true,\\n                    title: const Text\\('CDN 设置', style: titleStyle\\),.*?                    \\},\\n                  \\),\\n(?=                SingleChildScrollView\\()", re.S)
    text, n = pattern.subn('                if (!isFileSource)\n                  ListTile(\n                    dense: true,\n                    title: const Text(\'本次播放 CDN\', style: titleStyle),\n                    leading: const Icon(MdiIcons.cloudPlusOutline, size: 20),\n                    subtitle: Text(\n                      \'当前：${videoDetailCtr.currentCdn.desc}\'\n                      \'${videoDetailCtr.isCdnLockedForCurrentPlayback ? " · 已锁定" : ""}\',\n                      style: subTitleStyle,\n                    ),\n                    onTap: () async {\n                      Get.back();\n                      final selected = await showPlaybackCdnDialog(\n                        this.context,\n                        current: videoDetailCtr.currentCdn,\n                        locked: videoDetailCtr.isCdnLockedForCurrentPlayback,\n                      );\n                      if (selected != null) {\n                        await videoDetailCtr.selectCdnForCurrentPlayback(selected);\n                      }\n                    },\n                  ),\n', text, count=1)
    if n != 1:
        raise RuntimeError(f'header CDN block: expected 1 match, got {n}')
    return text

edit("lib/pages/video/introduction/local/view.dart", local_view)
edit("lib/pages/video/controller.dart", controller)
edit("lib/pages/setting/models/video_settings.dart", video_settings)
edit("lib/pages/video/widgets/header_control.dart", header)
print("large-file transformations complete")
