name: Build for Windows x64

on:
  workflow_call:
    inputs:
      tag:
        description: "tag"
        required: false
        default: ""
        type: string
      build_number:
        description: "Build number (0 = auto)"
        required: false
        default: "0"
        type: string
      include_portable:
        description: "Create portable ZIP"
        required: false
        default: true
        type: boolean
  workflow_dispatch:

jobs:
  build-windows-app:
    name: Release Windows x64
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Add fastforge and Inno Setup
        run: |
          dart pub global activate fastforge
          choco install innosetup

      - name: Add Chinese language file for Inno Setup
        run: |
          Copy-Item "windows/packaging/exe/ChineseSimplified.isl" "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl"
        shell: pwsh

      - name: Set and Extract version
        shell: pwsh
        env:
          BUILD_NUMBER_OVERRIDE: ${{ inputs.build_number }}
          RELEASE_TAG_OVERRIDE: ${{ inputs.tag }}
        run: lib/scripts/build.ps1

      - name: Apply Patch
        shell: pwsh
        run: lib/scripts/patch.ps1 windows

      - name: Apply media_kit decoder lab patch
        shell: pwsh
        run: lib/scripts/patch_media_kit_decoder_lab.ps1

      - name: Build Windows
        run: |
          fastforge package --platform windows --targets exe --flutter-build-args="dart-define-from-file=pili_release.json,no-pub" --skip-clean

      - name: Prepare Upload
        run: |
          mkdir -p Release/PiliBro-Win
          mkdir -p PiliBro-Win-Setup
          mv build/windows/x64/runner/Release/* Release/PiliBro-Win/
          mv dist/**/*.exe PiliBro-Win-Setup/PiliBro_windows_${{env.version}}_x64_setup.exe

      - name: Compress portable ZIP
        if: ${{ inputs.include_portable }}
        run: |
          Compress-Archive -Path "Release/PiliBro-Win" -DestinationPath "PiliBro_windows_${{env.version}}_x64_portable.zip"
        shell: pwsh

      - name: Upload windows portable release
        if: ${{ inputs.include_portable }}
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: Windows-file-x64-release
          path: PiliBro_windows_*.zip

      - name: Upload windows setup release
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: Windows-setup-x64-release
          path: PiliBro-Win-Setup/PiliBro_windows_*.exe
